### PR TITLE
Change item dialogue to only trigger when pressing Accept

### PR DESCRIPTION
**Pull request by jtran**
With this change, dialogue won't trigger automatically when you collide.  You have to press Space.

When you collide with an area that has dialogue, that is stored on the DialogueActor component.  This gives us a natural way to display in the UI that the player can talk or otherwise interact with an object.  This part isn't implemented yet.

### CODE REVIEW

**Comment by dmtaub** [comment]
Cool, is it still possible to trigger messages simply by colliding? I believe the doc calls for both. I can take a more in-depth look at the changes tonight

**Comment by jtran** [comment]
No, I didn't think we needed that.  But it's a pretty simple change to add that back.  My only question would be how to differentiate between the two.

**Comment by dmtaub** [comment]
Maybe "dialogue" versus "message" ? We can change the UI for them later,
but I think we will want something for the win condition at least that
doesn't require button press. That may be yet a third type, that kicks you
back to "menu" but with an extra message up about winning.

[image: Screen Shot 2021-03-26 at 1.44.51 PM.png]

>

**Review by dmtaub — APPROVED** [review]
distinct improvement. works well.

**Pull request merged**
